core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('services.urls', namespace='services')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.urls import path
from . import views
from .views import AgendaView,CustomLoginView, CustomLogoutView,AgregarUsuarioViews, CajaUpdateView,CajaListView,AgregarCajaView,EliminarUsuarioView, TipoServicioListView,editar_cliente, TipoServicioUpdateView, TipoServicioDeleteView, AgregarUsuarioView,ListarUsuariosView, ActualizarUsuarioView


app_name = 'services'

urlpatterns = [
    path('', views.homes, name='home'),
    # Otras rutas de la aplicación
    #clientes vistas
    path('clientes/agregar/',views.agregar_cliente, name='agregar_cli'),
    path('clientes/lista/',views.listar_clientes,name='listacli'),
    path('clientes/editar/<int:cliente_id>/', editar_cliente, name='editar_cliente'),

    #Gerente
    path('gerente/servicios/agregar',views.crear_tipo_servicio, name='agregarserv'),
    path('gerente/servicios', TipoServicioListView.as_view(), name='tipo_servicio_list'),
    path('gerente/servicios/editar/<int:pk>/', TipoServicioUpdateView.as_view(), name='actualizar_servicio'),
    path('gerente/servicios/eliminar/<int:pk>/', TipoServicioDeleteView.as_view(), name='eliminar_servicio'),

    #usuarios
    path('usuarios/agregar', AgregarUsuarioView.as_view(), name='agregar_usuario'),
    path('usuarios/listar', ListarUsuariosView.as_view(), name='listar_usuarios'),
    path('usuarios/editar/<int:pk>/', ActualizarUsuarioView.as_view(), name='actualizar_usuario'),
    path('usuarios/eliminar/<int:pk>/', EliminarUsuarioView.as_view(), name='eliminar_usuario'),

    #caja
    path('caja/agregar', AgregarCajaView.as_view(), name='agregar_caja'),
    path('caja/listar', CajaListView.as_view(), name='listar_cajas'),
    path('caja/editar/<int:pk>/', CajaUpdateView.as_view(), name='editar_caja'),


    #super

    path('agregar_usuariosup/', AgregarUsuarioViews.as_view(), name='agregar_usuariosup'),

    #log

    path('login/', CustomLoginView.as_view(), name='logins'),
    path('logout/', CustomLogoutView.as_view(), name='logouts'),

    #vista agenda

     path('agenda/', AgendaView.as_view(), name='agenda_view'),


    
    
]

services/forms.py
from .models import Cliente,TipoServicio,CustomUser,Caja
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.core.validators import MinLengthValidator

class ClienteForm(forms.ModelForm):
    fecha_atencion = forms.DateField(
        widget=forms.widgets.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
        label='Fecha de Atención'
    )
    hora_atencion = forms.TimeField(
        widget=forms.widgets.TimeInput(attrs={'type': 'time', 'class': 'form-control'}),
        label='Hora de Atención'
    )

    class Meta:
        model = Cliente
        fields = ['nombre', 'fecha_atencion', 'hora_atencion', 'email', 'telefono', 'servicio_realizado', 'personal_atencion']
        labels = {
            'nombre': 'Nombre',
            'fecha_atencion': 'Fecha de Atención',
            'hora_atencion': 'Hora de Atención',
            'email': 'Correo Electrónico',
            'telefono': 'Teléfono',
            'servicio_realizado': 'Servicio Realizado',
            'personal_atencion': 'Personal de Atención',
        }
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'fecha_atencion': forms.widgets.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'hora_atencion': forms.widgets.TimeInput(attrs={'type': 'time', 'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'telefono': forms.TextInput(attrs={'class': 'form-control', 'pattern': '\d{10}', 'title': 'El número de teléfono debe contener 10 dígitos'}),
            'servicio_realizado': forms.Select(attrs={'class': 'form-control'}),
            'personal_atencion': forms.Select(attrs={'class': 'form-control'}),
        }


class TipoServicioForm(forms.ModelForm):
    class Meta:
        model = TipoServicio
        fields = ['nombre_servicio', 'quien_ofrece', 'detalles_servicio', 'imagen', 'duration', 'costo_servicio']
        labels = {
            'nombre_servicio': 'Nombre del Servicio',
            'quien_ofrece': 'Quién Ofrece el Servicio',
            'detalles_servicio': 'Detalles del Servicio',
            'imagen': 'Imagen del Servicio',
            'duration': 'Duración del Servicio',
            'costo_servicio': 'Costo del Servicio',
        }

    nombre_servicio = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    quien_ofrece = forms.ModelChoiceField(
        queryset=CustomUser.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    detalles_servicio = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 4})
    )

    imagen = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={'class': 'form-control'})
    )

    duration = forms.DurationField(
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    costo_servicio = forms.DecimalField(
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

#  formset para TipoServicio



class CustomUserCreationForm(UserCreationForm):
    ROLES = (
        ('caja', 'Caja'),
        ('gerente', 'Gerente'),
        ('personal_servicio', 'Personal de Servicio'),
    )

    email = forms.EmailField(required=True)
    imagen = forms.ImageField(required=False)
    rol = forms.ChoiceField(choices=ROLES, required=True)

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'imagen', 'rol', 'password1', 'password2')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.imagen = self.cleaned_data['imagen']
        user.rol = self.cleaned_data['rol'].lower() 
        if commit:
            user.save()
        return user


# carrito

class CajaForm(forms.ModelForm):
    class Meta:
        model = Caja
        fields = ['personal_que_atendio', 'servicio_realizado', 'monto_total']

    def clean(self):
        cleaned_data = super().clean()
        personal_que_atendio = cleaned_data.get('personal_que_atendio')
        servicio_realizado = cleaned_data.get('servicio_realizado')

        if personal_que_atendio and servicio_realizado:
            if servicio_realizado.quien_ofrece != personal_que_atendio:
                raise forms.ValidationError("El personal que atendió no ofrece ese servicio.")

        
        costo_servicio = servicio_realizado.costo_servicio if servicio_realizado else 0

        
        cleaned_data['monto_total'] = costo_servicio

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['personal_que_atendio'].queryset = CustomUser.objects.filter(rol='personal_servicio')
       

    #login

class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password']

        

services/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .forms import ClienteForm,TipoServicioForm, CustomUserCreationForm, CajaForm,CustomAuthenticationForm
from django.views import View
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import DeleteView, UpdateView
from .models import TipoServicio,Cliente,CustomUser,Caja
from django.contrib.auth.views import LoginView, LogoutView
from .decorators import caja_login_required,gerente_login_required
from django.utils.decorators import method_decorator
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseNotFound, HttpResponseServerError


import logging

logger = logging.getLogger(__name__)



# Create your views here.

def homes(request):
    return render(request, 'serviceshtml/home.html', {})


#vistas cliente
    #agregar
def agregar_cliente(request):
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            logger.info('Cliente agregado con éxito')
            return redirect('services:home')  
        else:
            logger.warning('Intento de agregar un cliente con datos inválidos')
    else:
        form = ClienteForm()
    return render(request, 'serviceshtml/agregar_cita.html', {'form': form})

    #enlistar
#@gerente_login_required
def listar_clientes(request):
    clientes = Cliente.objects.all()
    return render(request, 'serviceshtml/listar_clientes.html', {'clientes': clientes})

    #actualizr informacion

#@gerente_login_required
def editar_cliente(request, cliente_id):
    cliente = get_object_or_404(Cliente, id=cliente_id)
    if request.method == 'POST':
        form = ClienteForm(request.POST, instance=cliente)
        if form.is_valid():
            form.save()
            logger.info(f'Cliente {cliente_id} editado con éxito por el gerente')
            return redirect('services:listacli')
        else:
            logger.warning(f'Intento de editar el cliente {cliente_id} con datos inválidos por el gerente')
    else:
        form = ClienteForm(instance=cliente)
    return render(request, 'serviceshtml/editar_cliente.html', {'form': form, 'cliente': cliente})



#servicios
    #crear nuevo servicio
#@gerente_login_required
def crear_tipo_servicio(request):
    if request.method == 'POST':
        form = TipoServicioForm(request.POST, request.FILES)
        if form.is_valid():
            # Validar 
            nuevo_tipo_servicio = form.save(commit=False)
            nuevo_tipo_servicio.save()
            logger.info('Nuevo tipo de servicio creado con éxito por el gerente')
            return redirect('services:home') 
        else:
            logger.warning('Intento de crear un nuevo tipo de servicio con datos inválidos por el gerente')
    else:
        form = TipoServicioForm()

    return render(request, 'serviceshtml/agregar_servicio.html', {'form': form})
    #editar servicios

class TipoServicioUpdateView(View):
    template_name = 'serviceshtml/actualizar_servicio.html'

 #   @method_decorator(gerente_login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request, pk):
        servicio = get_object_or_404(TipoServicio, pk=pk)
        form = TipoServicioForm(instance=servicio)
        return render(request, self.template_name, {'form': form, 'servicio': servicio})

    def post(self, request, pk):
        servicio = get_object_or_404(TipoServicio, pk=pk)
        form = TipoServicioForm(request.POST, instance=servicio)
        if form.is_valid():
            form.save()
            return redirect('services:tipo_servicio_list') 
        return render(request, self.template_name, {'form': form, 'servicio': servicio})

    #eliminar 

class TipoServicioDeleteView(DeleteView):
    model = TipoServicio
    template_name = 'serviceshtml/eliminar_servicio.html'  
    success_url = reverse_lazy('services:tipo_servicio_list')  

  #  @method_decorator(gerente_login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_object(self, queryset=None):
        return TipoServicio.objects.get(pk=self.kwargs['pk'])
    

    
#enlistar 


class TipoServicioListView(ListView):
    model = TipoServicio
    template_name = 'serviceshtml/tipo_servicio_list.html'  
    context_object_name = 'tipos_servicio'
   # @method_decorator(gerente_login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


#usuario (aun en desarrollo / hay problemas)

    #registrar 

class AgregarUsuarioView(View):
    template_name = 'serviceshtml/agregar_user.html'

    #@method_decorator(gerente_login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request):
        form = CustomUserCreationForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            logger.info('Nuevo usuario agregado con éxito por el gerente')

            return redirect('services:tipo_servicio_list')  
        else:
            logger.warning('Intento de agregar un nuevo usuario con datos inválidos por el gerente')

        return render(request, self.template_name, {'form': form})


    #enlistar

class ListarUsuariosView(View):
    template_name = 'serviceshtml/listar_usuarios.html' 

    #@method_decorator(gerente_login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request):
        usuarios = CustomUser.objects.all()
        return render(request, self.template_name, {'usuarios': usuarios})
    
    #actualizar

class ActualizarUsuarioView(View):
    template_name = 'serviceshtml/actualizar_usuario.html' 

    #@method_decorator(gerente_login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs) 

    def get(self, request, pk):
        usuario = get_object_or_404(CustomUser, pk=pk)
        form = CustomUserCreationForm(instance=usuario)
        return render(request, self.template_name, {'form': form, 'usuario': usuario})

    def post(self, request, pk):
        usuario = get_object_or_404(CustomUser, pk=pk)
        form = CustomUserCreationForm(request.POST, instance=usuario)
        if form.is_valid():
            form.save()
            logger.info(f'Usuario {pk} actualizado con éxito por el gerente')

            return redirect('services:listar_usuarios')  
        else:
            logger.warning(f'Intento de actualizar el usuario {pk} con datos inválidos por el gerente')

        return render(request, self.template_name, {'form': form, 'usuario': usuario})
    
    #eliminar

class EliminarUsuarioView(View):
    template_name = 'serviceshtml/eliminar_usuario.html' 

    #@method_decorator(gerente_login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request, pk):
        usuario = get_object_or_404(CustomUser, pk=pk)
        return render(request, self.template_name, {'usuario': usuario})

    def post(self, request, pk):
        usuario = get_object_or_404(CustomUser, pk=pk)
        logger.info(f'Usuario {pk} eliminado con éxito por el gerente')
        usuario.delete()
        return redirect('services:listar_usuarios') 


#vistas de caja

    #agregar

class AgregarCajaView(View):
    template_name = 'serviceshtml/agregar_caja.html' 

    #@method_decorator(caja_login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
    

    def get(self, request):
        form = CajaForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = CajaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('services:home')  
        return render(request, self.template_name, {'form': form})

    #enlistar caja

class CajaListView(ListView):
    model = Caja
    template_name = 'serviceshtml/listar_cajas.html'  
    context_object_name = 'cajas'

    #@method_decorator(caja_login_required)
    def dispatch(self, *args, **kwargs):
        try:
            logging.info('Este es un mensaje informativo')
        except Exception as e:
           
            logging.error(f"Error en la vista: {e}")
            return HttpResponse("Error interno del servidor", status=500)

        return super().dispatch(*args, **kwargs)


    #update


class CajaUpdateView(UpdateView):
    model = Caja
    form_class = CajaForm
    template_name = 'serviceshtml/editar_caja.html'  
    success_url = reverse_lazy('services:listar_cajas')

    #@method_decorator(caja_login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def post(self, request, *args, **kwargs):
        logger.info('Intento de actualización de caja a través de POST')
        return super().post(request, *args, **kwargs)


    #core seguridad
class AgregarUsuarioViews(View):
    template_name = 'serviceshtml/template_super.html'

    #@method_decorator(gerente_login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request):
        form = CustomUserCreationForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = CustomUserCreationForm(request.POST)
        try:
            if form.is_valid():
                user = form.save(commit=False)
                user.is_staff = True
                user.is_superuser = True
                user.save()

services/templates/serviceshtml/actualizar_servicio.html
{% extends "bases.html" %}
{% block content %}
<title>Gerente - Actualizar Servicio</title>

<section class="text-center text lg start" style="background-size:contain;
  background-color: rgba(0,0,0,0.6);
  background-repeat: no-repeat;
  height: 100vh;
  background-image: url('/media/imagenes_servicio/balan.jpg');
  backdrop-filter: blur(30px);">

  <style>
    .cascading-right {
      margin-right: -50px;
    }

    @media (max-width: 991.98px) {
      .cascading-right {
        margin-right: 0;
      }
    }
  </style>
  <!-- Jumbotron -->
  <div class="container py-4 align-center">
    <div class="row g-0 align-items-center">
      <div class="col-lg-6 mb-5 mb-lg-0">
        <div class="card cascading-right" style="background: hsla(0, 0%, 100%, 0.55);
              backdrop-filter: blur(30px);">
          <div class="card-body p-5 shadow-5 text-center">
            <h2 class="fw-bold mb-5">Editar servicio</h2>
            <form method="post">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit" class="btn btn-primary">Guardar cambios</button>
            </form>
          </div>
        </div>
      </div>
  <!-- Jumbotron -->
</section>

<!-- Agrega los scripts de Bootstrap 5 JS al final del cuerpo del documento -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"></script>


{% endblock content %}

services/templates/serviceshtml/agenda.html
{% extends "bases.html" %}

{% block content %}

aqui va la agenda

<h1>Agenda para {{ user.username }}</h1>
<ul>
    {% for evento in agenda %}
        <li>{{ evento.nombre }} - {{ evento.fecha_atencion }} {{ evento.hora_atencion }}</li>
    {% endfor %}
</ul>


{% endblock content %}

services/templates/serviceshtml/agregar_caja.html
{% extends "bases.html" %}

{% block content %}
<section class="text-center text lg start" style="background-size: cover;
  background-color: rgba(0,0,0,0.6);
  background-repeat: no-repeat;
  height: 100vh;
  background-image: url('/media/imagenes_servicio/balan.jpg');
  backdrop-filter: blur(30px);">

    <style>
        .cascading-right {
            margin-right: -50px;
        }

        @media (max-width: 991.98px) {
            .cascading-right {
                margin-right: 0;
            }
        }
    </style>
    <!-- Jumbotron -->
    <div class="container py-4">
        <div class="row g-0 align-items-center">
            <div class="col-lg-6 mb-5 mb-lg-0">
                <div class="card cascading-right" style="background: hsla(0, 0%, 100%, 0.55);
              backdrop-filter: blur(30px);">
                    <div class="card-body p-5 shadow-5 text-center">
                        <h2 class="fw-bold mb-5">Agregar Caja</h2>
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Guardar</button>
                        </form>
                    </div>
                    <a class="btn btn-danger" href="{% url 'services:home' %}">Cancelar</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Jumbotron -->

</section>

<!-- Agrega los scripts de Bootstrap 5 JS al final del cuerpo del documento -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"></script>

{% endblock content %}

services/templates/serviceshtml/agregar_servicio.html
{% extends "bases.html" %}

{% block content%}
<title>Gerente - Agregar Servicio</title>
<section class="text-center text-lg-start" style="background-size:cover;
  background-color: rgba(0, 0, 0, 0.6);
  background-repeat:space;
  height: 100vh;
  background-image: url('/media/imagenes_servicio/balan.jpg');
  backdrop-filter: blur(30px);">
  <style>
    .cascading-right {
      margin-right: -50px;
    }

    @media (max-width: 991.98px) {
      .cascading-right {
        margin-right: 0;
      }
    }
  </style>

  <!-- Jumbotron -->
  <div class="container py-4">
    <div class="row g-0 align-items-center">
      <div class="col-lg-6 mb-5 mb-lg-0">
        <div class="card cascading-right" style="
              background: hsla(0, 0%, 100%, 0.55);
              backdrop-filter: blur(30px);">
          <div class="card-body p-5 shadow-5 text-center">
            <h2 class="fw-bold mb-5">Agrega servicio</h2>
            <form method="post" id="tipoServicioForm" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit" class="btn btn-primary">Guardar</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Jumbotron -->
</section>
<!-- Agrega los scripts de Bootstrap 5 JS al final del cuerpo del documento -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"></script>

{% endblock content%}

services/templates/serviceshtml/listar_cajas.html
{% extends "bases.html" %}

{% block content %}
<title>Gerente - Lista de Cajas</title>

<section class="text-center text lg start" style="background-size:cover;
  background-color: rgba(0,0,0,0.6);
  background-repeat: no-repeat;
  height: 100vh;
  background-image: url('/media/imagenes_servicio/balan.jpg');
  backdrop-filter: blur(30px);">

    <style>
        .cascading-right {
            margin-right: -50px;
        }

        @media (max-width: 991.98px) {
            .cascading-right {
                margin-right: 0;
            }
        }
    </style>
    <div >
    <table class="table table-striped" style="background: hsla(0, 0%, 100%, 0.55); backdrop-filter: blur(30px);">
        <h2>Listado de Cajas</h2>
        {% for caja in cajas %}
        <thead>
            <tr>
                <th scope="col">Caja</th>
                <th scope="col">Acciones</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ caja }}</td>
                <td><a class="btn btn-primary" href="{% url 'services:editar_caja' caja.id %}">Editar</a></td>
            </tr>

        </tbody>

        {% endfor %}
    </table>
    </div>
</section>

{% endblock content %}

services/templates/serviceshtml/listar_clientes.html
{% extends "bases.html" %}

{% block content %}
<title>Gerente - Lista de Clientes</title>

<section class="text-center text lg start" style="background-size:cover;
  background-color: rgba(0,0,0,0.6);
  background-repeat: no-repeat;
  height: 100vh;
  background-image: url('/media/imagenes_servicio/balan.jpg');
  backdrop-filter: blur(30px);">

  <style>
    .cascading-right {
      margin-right: -50px;
    }

    @media (max-width: 991.98px) {
      .cascading-right {
        margin-right: 0;
      }
    }
  </style>

  <table class="table table-striped" style="background: hsla(0, 0%, 100%, 0.55);
backdrop-filter: blur(30px);">
    <h2>Listado de Clientes</h2>

    <thead>
      <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Fecha</th>
        <th scope="col">Hora</th>
        <th scope="col">Email</th>
        <th scope="col">Telefono</th>
        <th scope="col">Servicio</th>
        <th scope="col">Empleado</th>
      </tr>
    </thead>
    {% for cliente in clientes %}
    <tbody>
      <tr>

        <td>{{ cliente.nombre }}</td>
        <td>{{ cliente.fecha_atencion }}</td>
        <td>{{ cliente.hora_atencion }}</td>
        <td>{{ cliente.email }}</td>
        <td>{{ cliente.telefono }}</td>
        <td>{{ cliente.servicio_realizado }}</td>
        <td>{{ cliente.personal_atencion }}</td>
        <td><a class="btn btn-primary" href="{% url 'services:editar_cliente' cliente.id %}">Editar</a></td>
      </tr>

    </tbody>
    
    {% endfor %}
  </table>
  <a class="btn btn-primary" href="{% url 'services:home' %}">Volver a la página principal</a>
</section>

{% endblock content %}

services/templates/serviceshtml/listar_usuarios.html
{% extends "bases.html" %}

{% block content %}
<title>Gerente - Lista de Usuarios</title>

<section class="text-center text lg start" style="background-size:cover;
  background-color: rgba(0,0,0,0.6);
  background-repeat: no-repeat;
  height: 100vh;
  background-image: url('/media/imagenes_servicio/balan.jpg');
  backdrop-filter: blur(30px);">

    <style>
        .cascading-right {
            margin-right: -50px;
        }

        @media (max-width: 991.98px) {
            .cascading-right {
                margin-right: 0;
            }
        }
    </style>

    <table class="table table-striped" style="background: hsla(0, 0%, 100%, 0.55);
    backdrop-filter: blur(30px);">
        <h2>Listado de Usuarios</h2>
        {% for usuario in usuarios %}
        <thead>
            <tr>
                <th scope="col">Nombre</th>
                <th scope="col">Correo electrónico</th>
                <th scope="col">Rol</th>
                <th scope="col">Acciones</th>
            </tr>
        </thead>
        <tbody>
            <tr>

                <td>{{ usuario.username }}</td>
                <td>{{ usuario.email }}</td>
                <td>{{ usuario.rol }}</td>
                <td><a class="btn btn-primary" href="{% url 'services:actualizar_usuario' usuario.id %}">Editar</a></td>
                <td><a class="btn btn-danger" href="{% url 'services:eliminar_usuario' usuario.id %}">eliminar</a></td>
            </tr>

        </tbody>

        {% endfor %}
    </table>
</section>

{% endblock content %}

services/templates/serviceshtml/tipo_servicio_list.html
{% extends "bases.html" %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/servicios.css' %}">
<link rel="stylesheet" href="{% static 'js/scripts.js' %}">

<section class="text-center text lg start" style="background-size: cover;
  background-color: rgba(0,0,0,0.6);
  background-repeat: no-repeat;
  height: 100vh;
  background-image: url('/media/imagenes_servicio/balan.jpg');
  backdrop-filter: blur(30px);">

  <style>
    .cascading-right {
      margin-right: -50px;
    }

    @media (max-width: 991.98px) {
      .cascading-right {
        margin-right: 0;
      }
    }
  </style>

  <div class="container-tsl">
    <h1 class="title">Lista de Tipos de Servicio</h1>
    <div class="row">
      {% for tipo_servicio in tipos_servicio %}
      <div class="card">
        {% if tipo_servicio.imagen %}
        <img src="{{ tipo_servicio.imagen.url }}" class="img-fluid" alt="Chicago Skyscrapers" />
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{ tipo_servicio.nombre_servicio }}</h5>
          <p class="card-text">{{ tipo_servicio.quien_ofrece.username }}</p>
        </div>
        <ul class="list-group list-group-light list-group-small">
          <li class="card-text"> {{ tipo_servicio.duration }}</li>
          <li class="card-text"> ${{ tipo_servicio.costo_servicio }}</li>

        </ul>
        <div class="card-body">
          <a href="{% url 'services:eliminar_servicio' pk=tipo_servicio.pk %}" class="card-link">Eliminar link</a>
          <a href="{% url 'services:actualizar_servicio' pk=tipo_servicio.pk %}" class="card-link">Editar link</a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock content %}