core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('services.urls', namespace='services')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.urls import path
from . import views
from .views import AgendaView,CustomLoginView, CustomLogoutView,AgregarUsuarioViews, CajaUpdateView,CajaListView,AgregarCajaView,EliminarUsuarioView, TipoServicioListView,editar_cliente, TipoServicioUpdateView, TipoServicioDeleteView, AgregarUsuarioView,ListarUsuariosView, ActualizarUsuarioView


app_name = 'services'

urlpatterns = [
    path('', views.homes, name='home'),
    # Otras rutas de la aplicación
    #clientes vistas
    path('clientes/agregar/',views.agregar_cliente, name='agregar_cli'),
    path('clientes/lista/',views.listar_clientes,name='listacli'),
    path('clientes/editar/<int:cliente_id>/', editar_cliente, name='editar_cliente'),

    #Gerente
    path('gerente/servicios/agregar',views.crear_tipo_servicio, name='agregarserv'),
    path('gerente/servicios', TipoServicioListView.as_view(), name='tipo_servicio_list'),
    path('gerente/servicios/editar/<int:pk>/', TipoServicioUpdateView.as_view(), name='actualizar_servicio'),
    path('gerente/servicios/eliminar/<int:pk>/', TipoServicioDeleteView.as_view(), name='eliminar_servicio'),

    #usuarios
    path('usuarios/agregar', AgregarUsuarioView.as_view(), name='agregar_usuario'),
    path('usuarios/listar', ListarUsuariosView.as_view(), name='listar_usuarios'),
    path('usuarios/editar/<int:pk>/', ActualizarUsuarioView.as_view(), name='actualizar_usuario'),
    path('usuarios/eliminar/<int:pk>/', EliminarUsuarioView.as_view(), name='eliminar_usuario'),

    #caja
    path('caja/agregar', AgregarCajaView.as_view(), name='agregar_caja'),
    path('caja/listar', CajaListView.as_view(), name='listar_cajas'),
    path('caja/editar/<int:pk>/', CajaUpdateView.as_view(), name='editar_caja'),


    #super

    path('agregar_usuariosup/', AgregarUsuarioViews.as_view(), name='agregar_usuariosup'),

    #log

    path('login/', CustomLoginView.as_view(), name='logins'),
    path('logout/', CustomLogoutView.as_view(), name='logouts'),

    #vista agenda

     path('agenda/', AgendaView.as_view(), name='agenda_view'),


    
    
]

services/forms.py
from .models import Cliente,TipoServicio,CustomUser,Caja
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.core.validators import MinLengthValidator

class ClienteForm(forms.ModelForm):
    fecha_atencion = forms.DateField(
        widget=forms.widgets.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
        label='Fecha de Atención'
    )
    hora_atencion = forms.TimeField(
        widget=forms.widgets.TimeInput(attrs={'type': 'time', 'class': 'form-control'}),
        label='Hora de Atención'
    )

    class Meta:
        model = Cliente
        fields = ['nombre', 'fecha_atencion', 'hora_atencion', 'email', 'telefono', 'servicio_realizado', 'personal_atencion']
        labels = {
            'nombre': 'Nombre',
            'fecha_atencion': 'Fecha de Atención',
            'hora_atencion': 'Hora de Atención',
            'email': 'Correo Electrónico',
            'telefono': 'Teléfono',
            'servicio_realizado': 'Servicio Realizado',
            'personal_atencion': 'Personal de Atención',
        }
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'fecha_atencion': forms.widgets.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'hora_atencion': forms.widgets.TimeInput(attrs={'type': 'time', 'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'telefono': forms.TextInput(attrs={'class': 'form-control', 'pattern': '\d{10}', 'title': 'El número de teléfono debe contener 10 dígitos'}),
            'servicio_realizado': forms.Select(attrs={'class': 'form-control'}),
            'personal_atencion': forms.Select(attrs={'class': 'form-control'}),
        }


class TipoServicioForm(forms.ModelForm):
    class Meta:
        model = TipoServicio
        fields = ['nombre_servicio', 'quien_ofrece', 'detalles_servicio', 'imagen', 'duration', 'costo_servicio']
        labels = {
            'nombre_servicio': 'Nombre del Servicio',
            'quien_ofrece': 'Quién Ofrece el Servicio',
            'detalles_servicio': 'Detalles del Servicio',
            'imagen': 'Imagen del Servicio',
            'duration': 'Duración del Servicio',
            'costo_servicio': 'Costo del Servicio',
        }

    nombre_servicio = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    quien_ofrece = forms.ModelChoiceField(
        queryset=CustomUser.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    detalles_servicio = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 4})
    )

    imagen = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={'class': 'form-control'})
    )

    duration = forms.DurationField(
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    costo_servicio = forms.DecimalField(
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

#  formset para TipoServicio



class CustomUserCreationForm(UserCreationForm):
    ROLES = (
        ('caja', 'Caja'),
        ('gerente', 'Gerente'),
        ('personal_servicio', 'Personal de Servicio'),
    )

    email = forms.EmailField(required=True)
    imagen = forms.ImageField(required=False)
    rol = forms.ChoiceField(choices=ROLES, required=True)

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'imagen', 'rol', 'password1', 'password2')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.imagen = self.cleaned_data['imagen']
        user.rol = self.cleaned_data['rol'].lower() 
        if commit:
            user.save()
        return user


# carrito

class CajaForm(forms.ModelForm):
    class Meta:
        model = Caja
        fields = ['personal_que_atendio', 'servicio_realizado', 'monto_total']

    def clean(self):
        cleaned_data = super().clean()
        personal_que_atendio = cleaned_data.get('personal_que_atendio')
        servicio_realizado = cleaned_data.get('servicio_realizado')

        if personal_que_atendio and servicio_realizado:
            if servicio_realizado.quien_ofrece != personal_que_atendio:
                raise forms.ValidationError("El personal que atendió no ofrece ese servicio.")

        
        costo_servicio = servicio_realizado.costo_servicio if servicio_realizado else 0

        
        cleaned_data['monto_total'] = costo_servicio

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['personal_que_atendio'].queryset = CustomUser.objects.filter(rol='personal_servicio')
       

    #login

class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password']

        

services/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .forms import ClienteForm,TipoServicioForm, CustomUserCreationForm, CajaForm,CustomAuthenticationForm
from django.views import View
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import DeleteView, UpdateView
from .models import TipoServicio,Cliente,CustomUser,Caja
from django.contrib.auth.views import LoginView, LogoutView
from .decorators import caja_login_required,gerente_login_required
from django.utils.decorators import method_decorator
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseNotFound, HttpResponseServerError


import logging

logger = logging.getLogger(__name__)



# Create your views here.

def homes(request):
    return render(request, 'serviceshtml/home.html', {})


#vistas cliente
    #agregar
def agregar_cliente(request):
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            logger.info('Cliente agregado con éxito')
            return redirect('services:home')  
        else:
            logger.warning('Intento de agregar un cliente con datos inválidos')
    else:
        form = ClienteForm()
    return render(request, 'serviceshtml/agregar_cita.html', {'form': form})

    #enlistar
#@gerente_login_required
def listar_clientes(request):
    clientes = Cliente.objects.all()
    return render(request, 'serviceshtml/listar_clientes.html', {'clientes': clientes})

    #actualizr informacion

#@gerente_login_required
def editar_cliente(request, cliente_id):
    cliente = get_object_or_404(Cliente, id=cliente_id)
    if request.method == 'POST':
        form = ClienteForm(request.POST, instance=cliente)
        if form.is_valid():
            form.save()
            logger.info(f'Cliente {cliente_id} editado con éxito por el gerente')
            return redirect('services:listacli')
        else:
            logger.warning(f'Intento de editar el cliente {cliente_id} con datos inválidos por el gerente')
    else:
        form = ClienteForm(instance=cliente)
    return render(request, 'serviceshtml/editar_cliente.html', {'form': form, 'cliente': cliente})



#servicios
    #crear nuevo servicio
#@gerente_login_required
def crear_tipo_servicio(request):
    if request.method == 'POST':
        form = TipoServicioForm(request.POST, request.FILES)
        if form.is_valid():
            # Validar 
            nuevo_tipo_servicio = form.save(commit=False)
            nuevo_tipo_servicio.save()
            logger.info('Nuevo tipo de servicio creado con éxito por el gerente')
            return redirect('services:home') 
        else:
            logger.warning('Intento de crear un nuevo tipo de servicio con datos inválidos por el gerente')
    else:
        form = TipoServicioForm()

    return render(request, 'serviceshtml/agregar_servicio.html', {'form': form})
    #editar servicios

class TipoServicioUpdateView(View):
    template_name = 'serviceshtml/actualizar_servicio.html'

 #   @method_decorator(gerente_login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request, pk):
        servicio = get_object_or_404(TipoServicio, pk=pk)
        form = TipoServicioForm(instance=servicio)
        return render(request, self.template_name, {'form': form, 'servicio': servicio})

    def post(self, request, pk):
        servicio = get_object_or_404(TipoServicio, pk=pk)
        form = TipoServicioForm(request.POST, instance=servicio)
        if form.is_valid():
            form.save()
            return redirect('services:tipo_servicio_list') 
        return render(request, self.template_name, {'form': form, 'servicio': servicio})

    #eliminar 

class TipoServicioDeleteView(DeleteView):
    model = TipoServicio
    template_name = 'serviceshtml/eliminar_servicio.html'  
    success_url = reverse_lazy('services:tipo_servicio_list')  

  #  @method_decorator(gerente_login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_object(self, queryset=None):
        return TipoServicio.objects.get(pk=self.kwargs['pk'])
    

    
#enlistar 


class TipoServicioListView(ListView):
    model = TipoServicio
    template_name = 'serviceshtml/tipo_servicio_list.html'  
    context_object_name = 'tipos_servicio'
   # @method_decorator(gerente_login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


#usuario (aun en desarrollo / hay problemas)

    #registrar 

class AgregarUsuarioView(View):
    template_name = 'serviceshtml/agregar_user.html'

    #@method_decorator(gerente_login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request):
        form = CustomUserCreationForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            logger.info('Nuevo usuario agregado con éxito por el gerente')

            return redirect('services:tipo_servicio_list')  
        else:
            logger.warning('Intento de agregar un nuevo usuario con datos inválidos por el gerente')

        return render(request, self.template_name, {'form': form})


    #enlistar

class ListarUsuariosView(View):
    template_name = 'serviceshtml/listar_usuarios.html' 

    #@method_decorator(gerente_login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request):
        usuarios = CustomUser.objects.all()
        return render(request, self.template_name, {'usuarios': usuarios})
    
    #actualizar

class ActualizarUsuarioView(View):
    template_name = 'serviceshtml/actualizar_usuario.html' 

    #@method_decorator(gerente_login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs) 

    def get(self, request, pk):
        usuario = get_object_or_404(CustomUser, pk=pk)
        form = CustomUserCreationForm(instance=usuario)
        return render(request, self.template_name, {'form': form, 'usuario': usuario})

    def post(self, request, pk):
        usuario = get_object_or_404(CustomUser, pk=pk)
        form = CustomUserCreationForm(request.POST, instance=usuario)
        if form.is_valid():
            form.save()
            logger.info(f'Usuario {pk} actualizado con éxito por el gerente')

            return redirect('services:listar_usuarios')  
        else:
            logger.warning(f'Intento de actualizar el usuario {pk} con datos inválidos por el gerente')

        return render(request, self.template_name, {'form': form, 'usuario': usuario})
    
    #eliminar

class EliminarUsuarioView(View):
    template_name = 'serviceshtml/eliminar_usuario.html' 

    #@method_decorator(gerente_login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request, pk):
        usuario = get_object_or_404(CustomUser, pk=pk)
        return render(request, self.template_name, {'usuario': usuario})

    def post(self, request, pk):
        usuario = get_object_or_404(CustomUser, pk=pk)
        logger.info(f'Usuario {pk} eliminado con éxito por el gerente')
        usuario.delete()
        return redirect('services:listar_usuarios') 


#vistas de caja

    #agregar

class AgregarCajaView(View):
    template_name = 'serviceshtml/agregar_caja.html' 

    #@method_decorator(caja_login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
    

    def get(self, request):
        form = CajaForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = CajaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('services:home')  
        return render(request, self.template_name, {'form': form})

    #enlistar caja

class CajaListView(ListView):
    model = Caja
    template_name = 'serviceshtml/listar_cajas.html'  
    context_object_name = 'cajas'

    #@method_decorator(caja_login_required)
    def dispatch(self, *args, **kwargs):
        try:
            logging.info('Este es un mensaje informativo')
        except Exception as e:
           
            logging.error(f"Error en la vista: {e}")
            return HttpResponse("Error interno del servidor", status=500)

        return super().dispatch(*args, **kwargs)


    #update


class CajaUpdateView(UpdateView):
    model = Caja
    form_class = CajaForm
    template_name = 'serviceshtml/editar_caja.html'  
    success_url = reverse_lazy('services:listar_cajas')

    #@method_decorator(caja_login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def post(self, request, *args, **kwargs):
        logger.info('Intento de actualización de caja a través de POST')
        return super().post(request, *args, **kwargs)


    #core seguridad
class AgregarUsuarioViews(View):
    template_name = 'serviceshtml/template_super.html'

    #@method_decorator(gerente_login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request):
        form = CustomUserCreationForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = CustomUserCreationForm(request.POST)
        try:
            if form.is_valid():
                user = form.save(commit=False)
                user.is_staff = True
                user.is_superuser = True
                user.save()

services/templates/base.html
<!--  Base.html  -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}SPA{% endblock %}</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>

<body>
    {% block content %}{% endblock content %}
</body>

</html>

services/templates/bases.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" type="image/x-icon" href="/media/spa.png" />

  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>

<body>
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <div class="container-fluid">
      <ul class="navbar-nav">

        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'services:agregar_usuariosup' %}">Agregar SuperUser</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'services:agregar_usuario' %}">Agregar Usuarios</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'services:listar_usuarios' %}">Listar Usuarios</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'services:agregarserv' %}">Agregar Servicios</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'services:tipo_servicio_list' %}">Servicios</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'services:listacli' %}">Clientes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'services:agregar_caja' %}">Caja</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'services:listar_cajas' %}">Lista de Caja</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'services:logouts' %}">Cerrar Sesión</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'services:logins' %}">Iniciar Sesión</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'services:home' %}">Inicio</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'services:agenda_view' %}">agenda</a>
        </li>
      </ul>
    </div>
  </nav>

  {% block content %}


  {% endblock content %}

</body>

</html>

services/templates/navbar.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="stylesheet" href="/static/css/home.css">
    <link rel="icon" type="image/x-icon" href="/media/spa.png" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200">
    <!-- link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    < Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet" />
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="#page-top">Spa</a>
            
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'services:home' %}">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'services:home' %}">
                            Nuestra clinica
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'services:agregarserv' %}">Servicios admin</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'services:home' %}">Cerrar sesión</a></li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{% url 'services:home' %}" class="nav-link">Iniciar sesión</a>
                    </li>
                    <li class="nav-item"><a href="{% url 'services:home' %}" class="nav-link">Registrarme</a></li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'services:agregar_cli' %}">Reserva online</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
        {% block content %}
        {% endblock %}

</body>

<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="/static/js/scripts.js"></script>
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<!-- * *                               SB Forms JS                               * *-->
<!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>

</html>